// DOMContentLoaded ensures that all of the content is loaded before executing the JavaScript below.
document.addEventListener('DOMContentLoaded', () => {
    // Selects the container element where the tiles will be added, and assigns it to the tileContainer variable.
    const tileContainer = document.getElementById('tile-container');
    // Determines the total number of tiles that will be generated.
    const numTiles = 100;

    // For loop that runs an equivalent number of times as the value of the numTiles variable. 
    for (let i=0; i < numTiles; i++) {
        // Creates the tile variable and assigns it to the creation of a new div in the HTML.
        const tile = document.createElement('div');

        // Adds the 'tile' class to the div created above.
        tile.classList.add('tile');
        // Set a unique ID for each tile using the loop index.
        tile.id = `tile-${i}`;
        // Creates the num variable andassigns it to the creation of a new paragraph element in the HTML.
        const num = document.createElement('p');
        // Targets the num variable and uses the textContent property to generate the appropriate text for each tile.
        num.textContent = `Day ${i + 1}`;
        //  Append the paragraph to the tile div
        tile.appendChild(num);

        // If statement that checks strictly local storage to see if each tile generated by the loop was previously marked as 'active'.
        if (localStorage.getItem(`tile-${i}`) === 'active') {
        // When the tile was previously marked as 'active', use the classList method to add the tile to the 'active' class.
            tile.classList.add('active');

            if (tile.classList.contains('active')) {
                localStorage.setItem(`tile-${i}`, 'active');
            }
        }
        // Adds an event listener to the tile variable that is triggered by the user clicking the tile. When the user
        // clicks the tile, the classList for 'active' is toggled and the tile ID is set to local storage, passing the tiles that
        // contain the active class
        tile.addEventListener('click', () => {

            tile.classList.toggle('active');
            localStorage.setItem(`tile-${i}`, tile.classList.contains('active') ? 'active' : '');
        });
        // Append the tile to the tileContainer child element.
        tileContainer.appendChild(tile);
    }
    
});



